"""Write (or check) KC_COORD_RULES in main.lua from the developer's two
columns in briefs/CONTEST_COORDINATORS.md -- never hand-typed.

    python tests/gen_coordinator_rules.py          rewrite the table in main.lua
    python tests/gen_coordinator_rules.py --check  exit 1 if main.lua drifted

The worksheet's left four columns are generated by tests/coordinator_table.py;
its right two are the developer's: *Contest types* (which of COOL / BEAUTY /
CUTE / SMART / TOUGH this coordinator may compete in; blank = any) and
*Signature* (the POKeMON they ALWAYS bring, replacing the pool; blank = keep
the pool). This script copies those into main.lua as

    KC_COORD_RULES = { SPRITE_X = { kinds = {...}, signature = {...} }, ... }

keyed by sprite id: a "custom rival" / "custom crowd" row is SPRITE_KC_<NAME>,
everything else SPRITE_<NAME>, spaces to underscores. Decisions applied
2026-09-02: 21 rows with type limits, 5 with signatures.
"""
import os, re, sys

here = os.path.dirname(os.path.abspath(__file__))
main = os.path.join(here, "..", "main.lua")
brief = os.path.join(here, "..", "..", "briefs", "CONTEST_COORDINATORS.md")
BEGIN = "  -- BEGIN KC_COORD_RULES (generated by tests/gen_coordinator_rules.py from briefs/CONTEST_COORDINATORS.md -- do not edit)"
END = "  -- END KC_COORD_RULES"
KINDS = {"COOL", "BEAUTY", "CUTE", "SMART", "TOUGH"}

rows = []
for line in open(brief, encoding="utf-8"):
    if not line.startswith("| ") or line.startswith("| Coordinator") or line.startswith("|---"):
        continue
    cells = [c.strip() for c in line.strip().strip("|").split("|")]
    if len(cells) < 6:
        continue
    name, drawn, _odds, _pool, kinds, sig = cells[:6]
    name = name.replace("**", "").strip()
    if not kinds and not sig:
        continue
    # custom rivals/crowd AND Larry (his own roll) are SPRITE_KC_*; a
    # Larry rule was being emitted as SPRITE_LARRY and ignored (code review)
    custom = drawn.startswith("custom") or drawn == "own roll"
    key = "SPRITE_" + ("KC_" if custom else "") + name.replace(" ", "_")
    ks = [k.strip().upper() for k in kinds.split(",") if k.strip()]
    bad = [k for k in ks if k not in KINDS]
    if bad:
        print(f"{name}: unknown contest type(s) {bad}"); sys.exit(2)
    ss = [s.strip().upper().replace(" ", "_") for s in sig.split(",") if s.strip()]
    rows.append((key, ks, ss))

lines = [BEGIN,
         "  -- sprite -> what the developer decided on the worksheet: the contest",
         "  -- types this coordinator may enter (absent = any) and the POKeMON they",
         "  -- always bring (absent = their pool).",
         "  local KC_COORD_RULES = {"]
for key, ks, ss in rows:
    parts = []
    if ks: parts.append("kinds = { " + ", ".join(f'"{k}"' for k in ks) + " }")
    if ss: parts.append("signature = { " + ", ".join(f'"{s}"' for s in ss) + " }")
    lines.append(f"    {key} = {{ {', '.join(parts)} }},")
lines += ["  }", END]
block = "\n".join(lines)

src = open(main, encoding="utf-8", newline="").read()
nl = "\r\n" if "\r\n" in src else "\n"
m = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S).search(src)
if not m:
    print("markers not found in main.lua"); sys.exit(2)
current = m.group(0).replace("\r\n", "\n")
if "--check" in sys.argv:
    if current == block:
        print(f"KC_COORD_RULES up to date ({len(rows)} coordinators)"); sys.exit(0)
    print("KC_COORD_RULES in main.lua DIFFERS from the worksheet -- rerun without --check"); sys.exit(1)
open(main, "w", encoding="utf-8", newline="").write(src[:m.start()] + block.replace("\n", nl) + src[m.end():])
print(f"wrote KC_COORD_RULES: {len(rows)} coordinators ({sum(1 for r in rows if r[1])} with type limits, {sum(1 for r in rows if r[2])} with signatures)")
