"""Write (or check) the KC_VANILLA_PALETTE table in main.lua from
sprites/VANILLA_OBJ_PALETTES.json -- never hand-typed.

    python tests/gen_vanilla_palettes.py          rewrite the table in main.lua
    python tests/gen_vanilla_palettes.py --check  exit 1 if main.lua drifted

Why: a vanilla sprite sheet's palette is only a DEFAULT; every vanilla
object_event overrides it (engine Palettes.objectPaletteId, `palette % 8`
when non-zero). 24 sheets default to a colour the game never shows -- Jasmine
green, Misty blue, Koga brown -- and our crowd spawned them that way (REQUESTS
row 11). The JSON is generated from the ROM by exchange/vanilla_palettes.py;
this script copies its "WRONG" rows (sheet default never used in vanilla) into
main.lua as the PAL_NPC value spawnMarked passes on the def. "mixed" sprites
keep their sheet default: it IS one of the colours vanilla uses.

The mod cannot read the JSON at run time (no filesystem in the sandbox, and
it is not in the zip), which is why the table is embedded and this check
exists.
"""
import json, os, re, sys

here = os.path.dirname(os.path.abspath(__file__))
main = os.path.join(here, "..", "main.lua")
jpath = os.path.join(here, "..", "..", "sprites", "VANILLA_OBJ_PALETTES.json")
BEGIN = "  -- BEGIN KC_VANILLA_PALETTE (generated by tests/gen_vanilla_palettes.py -- do not edit)"
END = "  -- END KC_VANILLA_PALETTE"

d = json.load(open(jpath, encoding="utf-8"))
rows = sorted((k[len("SPRITE_"):], v) for k, v in d["sprites"].items() if v.get("verdict") == "WRONG")
lines = [BEGIN,
         "  -- sprite -> PAL_NPC value (8 + PAL_OW index): the colour vanilla",
         "  -- actually shows, for every sheet whose default vanilla never uses.",
         "  local KC_VANILLA_PALETTE = {"]
for name, v in rows:
    lines.append(f'    {name} = {v["recommended"]},  -- sheet {v["sheet_default"][7:]}, vanilla {v["recommended_name"][8:]}')
lines += ["  }", END]
block = "\n".join(lines)

src = open(main, encoding="utf-8", newline="").read()
nl = "\r\n" if "\r\n" in src else "\n"
pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
m = pat.search(src)
if not m:
    print("markers not found in main.lua"); sys.exit(2)
current = m.group(0).replace("\r\n", "\n")
if "--check" in sys.argv:
    if current == block:
        print(f"KC_VANILLA_PALETTE up to date ({len(rows)} sprites)"); sys.exit(0)
    print("KC_VANILLA_PALETTE in main.lua DIFFERS from sprites/VANILLA_OBJ_PALETTES.json -- rerun without --check")
    sys.exit(1)
new = src[:m.start()] + block.replace("\n", nl) + src[m.end():]
open(main, "w", encoding="utf-8", newline="").write(new)
print(f"wrote KC_VANILLA_PALETTE: {len(rows)} sprites")
